# docker-compose.yaml
# Mailhog

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    volumes:
      - mailhog:/var/lib/mailhog



volumes:
  mailhog:



# networks:
#   postgres-network:
#     driver: bridge