# docker-compose.yaml
# Mailhog

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    volumes:
      - mailhog:/var/lib/mailhog
  
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-stack:/var/lib/redis
    environment:
      - REDIS_ARGS=--save 900 1



volumes:
  mailhog:
  redis-stack:



# networks:
#   postgres-network:
#     driver: bridge